/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import ejercisio2practico3.Paciente;

/**
 *
 * @author Administrador
 */
public class ingresar_paciente extends javax.swing.JFrame {

    /**
     * Creates new form ingresar_medico
     */
    public ingresar_paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_NombreAp = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jTextField_Documento = new javax.swing.JTextField();
        jTextField_Fechadenacimiento = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextField_Correo = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField_Telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Correo :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jLabel3.setText("Nombre Apellido : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel4.setText("Sexo : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setText("Direccion : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setText("Documento : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setText("Fecha de nacimeiento :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, 20));

        jLabel9.setText("Telefono : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jTextField_NombreAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NombreApActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_NombreAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 270, -1));
        jPanel1.add(jTextFieldSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 270, -1));
        jPanel1.add(jTextField_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 270, -1));
        jPanel1.add(jTextField_Fechadenacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 270, -1));
        jPanel1.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 270, -1));
        jPanel1.add(jTextField_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 270, -1));

        jToggleButton1.setText("Volver");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 120, -1));

        jToggleButton2.setText("Ingresar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));
        jPanel1.add(jTextField_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Paciente nuevo = new Paciente();
        try{
            nuevo.NombreApellido(jTextField_NombreAp.getText());
            nuevo.Correo(jTextField_Correo.getText());
            nuevo.Direccion(jTextFieldDireccion.getText());
            nuevo.Documento(jTextField_Documento.getText());
            nuevo.Fechadenacimeiento(jTextField_Fechadenacimiento.getText());
            nuevo.Telefono(jTextField_Telefono.getText());
            nuevo.Sexo(jTextFieldSexo.getText());
   
            }catch(exepcion e) {
                
            }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField_NombreApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NombreApActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NombreApActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresar_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextField_Correo;
    private javax.swing.JTextField jTextField_Documento;
    private javax.swing.JTextField jTextField_Fechadenacimiento;
    private javax.swing.JTextField jTextField_NombreAp;
    private javax.swing.JTextField jTextField_Telefono;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
